# Generated by Django 6.1.1 on 2026-09-30 17:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=512)),
                ('source_row_number', models.PositiveIntegerField()),
                ('opis_truckstop_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=512)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=16)),
                ('rack_id', models.CharField(max_length=32)),
                ('retail_price', models.DecimalField(decimal_places=8, max_digits=12)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('display_name', models.TextField(blank=True)),
                ('geocoding_status', models.CharField(choices=[('pending', 'Pending'), ('geocoded', 'Geocoded'), ('no_match', 'No match'), ('error', 'Error')], default='pending', max_length=16)),
                ('geocoding_error', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['source_file', 'source_row_number'],
                'constraints': [models.UniqueConstraint(fields=('source_file', 'source_row_number'), name='unique_fuel_station_source_row')],
            },
        ),
    ]
