# Generated by Django 6.1.1 on 2026-10-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='osm_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
