# Generated by Django 6.1.1 on 2026-10-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('request', models.JSONField()),
                ('response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'db_table': 'routes_cache',
            },
        ),
    ]
